name: actions
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: |
          apt install python
        uses: actions/checkout@v2
        run:
          python hello.py
      - name: list files
        run: |
          pwd
          ls
          git status
