name: actions
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: list files
        run: |
          apt install python
          python hello.py
          pwd
          ls
          git status
