name: shell commands
on: [push]

jobs:
  runs-shell-command:
    runs-on:  ubuntu-latest
    steps:
      - name: echo a string
        run:  echo "Hello"
      - name: multiline script
        run:  |
          node -v
          npm -v
